spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${DB_URL}
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  jwt:
    secretKey: ${JWT_SECRET}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}
    header: ${HEADER}
    prefix: ${PREFIX}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}


  cloud:
    aws:
      bucket: ${BUCKET_NAME}
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
      region: ap-northeast-2
      stack:
        auto: false

  ai:
    base-url: ${AI_BASE_URL}


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.http.converter.json: DEBUG
    # SQL + 바인딩 값까지 보고 싶다면 추가:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


