spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_TEST_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jwt:
    secretKey: ${JWT_SECRET}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}
    header: ${HEADER}
    prefix: ${PREFIX}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}


  cloud:
    aws:
      bucket: ${BUCKET_NAME}
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
      region: ap-northeast-2
      stack:
        auto: false